#pragma once

extern const u8 ssl_quicksand[];
extern const u8 ssl_pyramid_sand[];
extern const u8 ttc_yellow_triangle[];

extern const Gfx castle_grounds_dl_waterfall[];
extern Movtex castle_grounds_movtex_tris_waterfall[];
extern Movtex ssl_movtex_tris_pyramid_sand_pathway_front[];
extern const Gfx ssl_dl_pyramid_sand_pathway_begin[];
extern const Gfx ssl_dl_pyramid_sand_pathway_end[];
extern const Gfx ssl_dl_pyramid_sand_pathway_front_end[];
extern Movtex ssl_movtex_tris_pyramid_sand_pathway_floor[];
extern const Gfx ssl_dl_pyramid_sand_pathway_floor_begin[];
extern const Gfx ssl_dl_pyramid_sand_pathway_floor_end[];
extern Movtex ssl_movtex_tris_pyramid_sand_pathway_side[];
extern const Gfx ssl_dl_pyramid_sand_pathway_side_end[];
extern Movtex bitfs_movtex_tris_lava_first_section[];
extern const Gfx bitfs_dl_lava_sections[];
extern Movtex bitfs_movtex_tris_lava_second_section[];
extern Movtex bitfs_movtex_tris_lava_floor[];
extern const Gfx bitfs_dl_lava_floor[];
extern Movtex lll_movtex_tris_lava_floor[];
extern const Gfx lll_dl_lava_floor[];
extern Movtex lll_movtex_tris_lavafall_volcano[];
extern const Gfx lll_dl_lavafall_volcano[];
extern Movtex cotmc_movtex_tris_water[];
extern const Gfx cotmc_dl_water_begin[];
extern const Gfx cotmc_dl_water_end[];
extern const Gfx cotmc_dl_water[];
extern Movtex ttm_movtex_tris_begin_waterfall[];
extern const Gfx ttm_dl_waterfall[];
extern Movtex ttm_movtex_tris_end_waterfall[];
extern Movtex ttm_movtex_tris_begin_puddle_waterfall[];
extern const Gfx ttm_dl_bottom_waterfall[];
extern Movtex ttm_movtex_tris_end_puddle_waterfall[];
extern Movtex ttm_movtex_tris_puddle_waterfall[];
extern const Gfx ttm_dl_puddle_waterfall[];
extern Movtex ssl_movtex_tris_pyramid_quicksand[];
extern const Gfx ssl_dl_quicksand_begin[];
extern const Gfx ssl_dl_quicksand_end[];
extern const Gfx ssl_dl_pyramid_quicksand[];
extern Movtex ssl_movtex_tris_pyramid_corners_quicksand[];
extern const Gfx ssl_dl_pyramid_corners_quicksand[];
extern Movtex ssl_movtex_tris_sides_quicksand[];
extern const Gfx ssl_dl_sides_quicksand[];
extern Movtex ttc_movtex_tris_big_surface_treadmill[];
extern const Gfx ttc_dl_surface_treadmill_begin[];
extern const Gfx ttc_dl_surface_treadmill_end[];
extern const Gfx ttc_dl_surface_treadmill[];
extern Movtex ttc_movtex_tris_small_surface_treadmill[];
extern Movtex ssl_movtex_tris_quicksand_pit[];
extern const Gfx ssl_dl_quicksand_pit_begin[];
extern const Gfx ssl_dl_quicksand_pit_end[];
extern const Gfx ssl_dl_quicksand_pit[];
extern Movtex ssl_movtex_tris_pyramid_quicksand_pit[];
extern const Gfx ssl_dl_pyramid_quicksand_pit_begin[];
extern const Gfx ssl_dl_pyramid_quicksand_pit_end[];


extern const struct MovtexQuadCollection bbh_movtex_merry_go_round_water_entrance[];
extern const struct MovtexQuadCollection bbh_movtex_merry_go_round_water_side[];
extern const struct MovtexQuadCollection ccm_movtex_penguin_puddle_water[];
extern const struct MovtexQuadCollection inside_castle_movtex_green_room_water[];
extern const struct MovtexQuadCollection inside_castle_movtex_moat_water[];
extern const struct MovtexQuadCollection hmc_movtex_dorrie_pool_water[];
extern const struct MovtexQuadCollection hmc_movtex_toxic_maze_mist[];
extern const struct MovtexQuadCollection ssl_movtex_puddle_water[];
extern const struct MovtexQuadCollection ssl_movtex_toxbox_quicksand_mist[];
extern const struct MovtexQuadCollection sl_movtex_water[];
extern const struct MovtexQuadCollection wdw_movtex_area1_water[];
extern const struct MovtexQuadCollection wdw_movtex_area2_water[];
extern const struct MovtexQuadCollection jrb_movtex_water[];
extern const struct MovtexQuadCollection jrb_movtex_intial_mist[];
extern const struct MovtexQuadCollection jrb_movtex_sinked_boat_water[];
extern const struct MovtexQuadCollection thi_movtex_area1_water[];
extern const struct MovtexQuadCollection thi_movtex_area2_water[];
extern const struct MovtexQuadCollection castle_grounds_movtex_water[];
extern const struct MovtexQuadCollection lll_movtex_volcano_floor_lava[];
extern const struct MovtexQuadCollection ddd_movtex_area1_water[];
extern const struct MovtexQuadCollection ddd_movtex_area2_water[];
extern const struct MovtexQuadCollection wf_movtex_water[];
extern const struct MovtexQuadCollection castle_courtyard_movtex_star_statue_water[];
extern const struct MovtexQuadCollection ttm_movtex_puddle[];
